//console.log(1);
//console.log(2);
//console.log(3);
f123();
console.log('A');
console.log('B');
console.log('C');
//console.log(1);
//console.log(2);
//console.log(3);
f123();
console.log('C');
console.log('D');
console.log('E');
//console.log(1);
//console.log(2);
//console.log(3);
f123();
console.log('E');
console.log('F');
console.log('G');
//console.log(1);
//console.log(2);
//console.log(3);
f123();

function f123()
{
  console.log(1);
  console.log(2);
  console.log(3);
  console.log(4);
}
